// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Packem.Integrations;

#nullable disable

namespace Packem.Integrations.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    partial class IntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Packem.Integrations.Entities.PurchaseOrderHeader", b =>
                {
                    b.Property<decimal>("po_no")
                        .HasColumnType("decimal(19,2)");

                    b.Property<DateTime?>("ExpectedShipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ack_code")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("ack_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("approved")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("auto_vouch_except_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("bid_no")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("blind_ship_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("branch_id")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("bulk_discount_flag")
                        .HasColumnType("char(1)");

                    b.Property<int?>("cad_cha_contract_cd")
                        .HasColumnType("int");

                    b.Property<string>("cad_cha_quote_no")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("canadian_b3_forms_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("cancel_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("carrier_id")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("closed_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("company_no")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("complete")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("contact_id")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("char(255)");

                    b.Property<decimal>("currency_id")
                        .HasColumnType("decimal(19,0)");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_due")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_last_modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<decimal>("dflt_list_price_multiplier")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("division_id")
                        .HasColumnType("decimal(19,0)");

                    b.Property<string>("do_not_export_carrier_po_flag")
                        .HasColumnType("char(1)");

                    b.Property<int>("edi_edit_count")
                        .HasColumnType("int");

                    b.Property<decimal>("estimated_value")
                        .HasColumnType("decimal(19,9)");

                    b.Property<string>("estimated_value_edit_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<decimal>("exchange_rate")
                        .HasColumnType("decimal(19,6)");

                    b.Property<string>("exclude_from_lead_time")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("expected_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("expedite_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("external_po_no")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("fob")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("historical_complete_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("last_maintained_by")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("location_id")
                        .HasColumnType("decimal(19,0)");

                    b.Property<string>("net_billing_flag")
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("order_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("packing_basis")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("packing_basis_violation_cd")
                        .HasColumnType("int");

                    b.Property<string>("packing_slip_number")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("period")
                        .HasColumnType("decimal(3,0)");

                    b.Property<string>("po_class1")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("po_class2")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("po_class3")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("po_class4")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("po_class5")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("po_desc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("po_hdr_uid")
                        .HasColumnType("int");

                    b.Property<int?>("po_qty_change_count")
                        .HasColumnType("int");

                    b.Property<string>("po_type")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("print_canadian_b3_forms_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("printed")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("purchase_group_id")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime?>("receipt_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("requested_by")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("retrieved_by_wms")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("revised_po")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("sales_order_number")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime?>("sent_to_carrier_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ship2_add1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ship2_add2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ship2_add3")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ship2_city")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ship2_country")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ship2_name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ship2_state")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ship2_zip")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ship_via_desc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("source_type")
                        .HasColumnType("int");

                    b.Property<decimal>("supplier_id")
                        .HasColumnType("decimal(19,0)");

                    b.Property<string>("supplier_release_no")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("terms")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("total_iva_tax_amt")
                        .HasColumnType("decimal(19,6)");

                    b.Property<string>("tracking_no")
                        .HasColumnType("char(40)");

                    b.Property<int?>("transmission_method")
                        .HasColumnType("int");

                    b.Property<string>("transmit_edi")
                        .HasColumnType("char(1)");

                    b.Property<string>("transmit_email")
                        .HasColumnType("char(1)");

                    b.Property<string>("transmit_fax")
                        .HasColumnType("char(1)");

                    b.Property<string>("transmit_print")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("vendor_id")
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("vendor_pays_freight_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("vouch_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<decimal>("year_for_period")
                        .HasColumnType("decimal(4,0)");

                    b.HasKey("po_no");

                    b.HasIndex("vendor_id");

                    b.ToTable("po_hdr", (string)null);
                });

            modelBuilder.Entity("Packem.Integrations.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<decimal>("po_no")
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("account_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acknowledged_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("b3_qty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("base_ut_price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bulk_buy_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cad_purchase_cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calc_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calc_value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cancel_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carrier_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("closed_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("combinable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contract_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_due")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_due_last_modified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_last_modified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delete_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desired_receipt_location_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edi_new_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entered_as_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exclude_from_lead_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exp_date_updates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expected_ship_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expedite_es")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expedite_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expedite_followup_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extended_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gpor_run_uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("in_bound_curry_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inv_mast_uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_maained_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("list_price_multiplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mfg_part_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("next_break")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("next_due_in_po_cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("next_ut_price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("original_unit_price_display")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parent_po_line_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_line_uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price_edit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_book_disc_grp_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_book_effective_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_book_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_book_item_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_book_supplier_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_unit_size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("purchase_pricing_page_uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("qty_ordered")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("qty_ready")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qty_ready_unit_size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qty_ready_uom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("qty_received")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("qty_to_vouch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_changed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("received_date")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("required_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("retrieved_by_wms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_ship_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_of_measure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unit_price_display")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_qty_ready")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vouch_completed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("po_no");

                    b.ToTable("po_line", (string)null);
                });

            modelBuilder.Entity("Packem.Integrations.Entities.Vendor", b =>
                {
                    b.Property<decimal>("vendor_id")
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vendor_id");

                    b.ToTable("vendor", (string)null);
                });

            modelBuilder.Entity("Packem.Integrations.Entities.PurchaseOrderHeader", b =>
                {
                    b.HasOne("Packem.Integrations.Entities.Vendor", "Vendors")
                        .WithMany("PurchaseOrderHeaders")
                        .HasForeignKey("vendor_id")
                        .IsRequired()
                        .HasConstraintName("FK_po_hdr_vendor");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("Packem.Integrations.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("Packem.Integrations.Entities.PurchaseOrderHeader", "PurchaseOrderHeader")
                        .WithMany()
                        .HasForeignKey("po_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrderHeader");
                });

            modelBuilder.Entity("Packem.Integrations.Entities.Vendor", b =>
                {
                    b.Navigation("PurchaseOrderHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
